### ISSUE TITLE
make the keyword case-insensitive

### ISSUE THREAD

**Issue by tiann** [offu/close-issue-app#62]
**Is your feature request related to a problem? Please describe.**  

The keyword seems case-sensitive.

**Describe the solution you'd like**  

make the keyword case-insensitive

**Describe alternatives you've considered**  

No.

**Additional context**  

Here is a issue dealt by the bot: https://github.com/android-hacker/VirtualXposed/issues/308

(You can read the edit history of the issue, i just change a Character and it works.

**Comment by helloqiu** [comment]
Thx for your suggestion.
This app uses `includes`, which is **case sensitive**, to check whether the issue body "includes" some keywords: https://github.com/offu/close-issue-app/blob/master/src/parser.ts#L19
And I believe this is a feature because this can make the process more strict.
However, it's a good idea to make this configurable. Currently you can just modify your config file. I'll add this feature soon.
@tiann

**Comment by tiann** [comment]
Thank you :)
